### ISSUE TITLE
谢谢！”Release版可执行文件为Windows 64bit，不需要安装任何依赖。“是指不用配置环境吗？

### ISSUE THREAD

**Issue by ysinx** [Aeroblast/UnpackKindleS#1]
我下载了可执行文件，就可以使用了，没配置环境。

**Comment by Aeroblast** [comment]
配置环境指的是这个项目之外需要的部分，也就是Kindle for PC，还有DRM Tools(以及配套的python环境)。程序本身运行不需要安装其他东西。

**Comment by ysinx** [comment]
大概明白了。我是用Calibre插件移除DRM，dedrm.bat没用上。
