### ISSUE TITLE
Merge azw and azw.res files

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [Aeroblast/UnpackKindleS#10]
Would it be possible to make a fast code to directly replace low-ress images in a kindle file with the hi-res versions that doesn't involve unpacking, manually replacing and then passing through kindlegen?

The only code I found anywhere for that is quite clunky...

**Comment by Aeroblast** [comment]
Unfortunately, I have not worked on such function. As you said, I keep books as EPUB and use kindlegen when I need kindle format.

I remember that someone did. 
Here : https://github.com/apprenticeharper/DeDRM_tools/pull/959
