### ISSUE TITLE
图片转换缺失

### ISSUE THREAD

**Issue by MilarvozM** [Aeroblast/UnpackKindleS#11]
漫画是 あの頃の青い星，全四卷都有这个问题
https://www.amazon.co.jp/-/en/dp/B07R9PNPPZ?binding=kindle_edition&ref=dbs_dp_rwt_sb_tukn
链接放一个在这里，是免费漫画所以可以直接实验

1: 53/54
2: 60/64
3: 92/98
4: 87/94

[lastrun.log](https://github.com/Aeroblast/UnpackKindleS/files/7070101/lastrun.log)
这是第三卷的log，只看这个的话是觉得直接跳过了缺失的那几页

是hi-res包本身就没那么多张图吗

**Comment by Aeroblast** [comment]
并不是所有图都在azw.res里有一份。根据观察，漫画、杂志类的书，当图片超过一定大小时（应该是800KB），才会在azw.res存一份图，在azw3里存一个降低压缩质量的图，二者分辨率相同。本身较小的图片则只会在azw3里出现。


如果想得到所有图片，请拆EPUB，然后解压。
