### ISSUE TITLE
遇到了这个问题不知道是哪里出错

### ISSUE THREAD

**Issue by yuekin** [Aeroblast/UnpackKindleS#12]
D:\BaiduYunDownload\My Kindle Content\B094C69KND_EBOK>cd /d D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\\app

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>UnpackKindleS "D:\BaiduYunDownload\My Kindle Content" .. -dedrm -batch --rename-xhtml-with-id
UnpackKindleS Ver.20210724
https://github.com/Aeroblast/UnpackKindleS
Batch Process:D:\BaiduYunDownload\My Kindle Content

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>"D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\\AZW3_PC_DeDRM.exe" "D:\BaiduYunDownload\My Kindle Content\B08X15T77B_EBOK\B08X15T77B_EBOK.azw"
Cannot find .azw3 file in D:\BaiduYunDownload\My Kindle Content\B08X15T77B_EBOK

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>"D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\\AZW3_PC_DeDRM.exe" "D:\BaiduYunDownload\My Kindle Content\B094C69KND_EBOK\B094C69KND_EBOK.azw"
Cannot find .azw3 file in D:\BaiduYunDownload\My Kindle Content\B094C69KND_EBOK

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>"D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\\AZW3_PC_DeDRM.exe" "D:\BaiduYunDownload\My Kindle Content\B09BCL7MLW_EBOK\B09BCL7MLW_EBOK.azw"
Cannot find .azw3 file in D:\BaiduYunDownload\My Kindle Content\B09BCL7MLW_EBOK

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>"D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\\AZW3_PC_DeDRM.exe" "D:\BaiduYunDownload\My Kindle Content\B09FJD6DFW_EBOK\B09FJD6DFW_EBOK.azw"
Cannot find .azw3 file in D:\BaiduYunDownload\My Kindle Content\B09FJD6DFW_EBOK

D:\UnpackKindleS_Release20210724_win_x64_AZW3DeDRM\app>pause
![QQ图片20210928003439](https://user-images.githubusercontent.com/87274643/134939776-7a6ed75d-2689-429e-8bde-78bda00e7968.png)

在bat里也更改了位置了
![QQ图片20210928003439](https://user-images.githubusercontent.com/87274643/134939937-9eed04a8-2c57-4803-89ab-d19702212153.png)
之前都能用但是突然找不到了，请问要怎么做才能重新用呢

**Comment by Aeroblast** [comment]
azw3是AZW3_PC_DeDRM程序的输出，也就是解密后的书。
从这个记录看不出AZW3_PC_DeDRM的运行结果，请试着单独解密一下，看看有没有什么报错。

**Comment by yuekin** [comment]
![QQ图片20210928223923](https://user-images.githubusercontent.com/87274643/135098578-e9d5a42a-6584-4a88-b09c-a5976a671217.png)
单独解密也是这样的

**Comment by Aeroblast** [comment]
不知道为什么，看上去AZW3_PC_DeDRM没有运行的迹象……
+ 请试着用AZW3_PC_DeDRM打开azw文件，比如把azw拖到AZW3_PC_DeDRM.exe上，确保解密工具可用。
+ 检查dedrm.bat内容是否正确指向AZW3_PC_DeDRM.exe位置。没动过的话应该没问题才对……

**Comment by yuekin** [comment]
用AZW3_PC_DeDRM打开azw文件直接闪退了
![$LTPE@EUG%)Q~T)N9%9VG`X](https://user-images.githubusercontent.com/87274643/135212585-488ee4f2-c1a5-4687-8016-446174a08f83.png)
AZW3_PC_DeDRM.exe的位置

**Comment by Aeroblast** [comment]
闪退是正常的，重要的是有没有出现azw3（看样子没有吧……）
尝试用命令行运行 AZW3_PC_DeDRM xxx.azw 看看输出结果
解密工具无法运行的可能性：
+ 那个玩意是py2写的，对中文路径支持不好（不过看上去你这个没问题）
+ k4i里缓存的登录信息失效（重新登陆Kindle客户端，删除k4i后重新运行解密工具）

**Comment by yuekin** [comment]
运行了 AZW3_PC_DeDRM xxx.azw之后出现的结果
![QQ图片20211001101930](https://user-images.githubusercontent.com/87274643/135551183-889c043b-8dd6-4579-9b26-065406ce904d.png)
另外重新登录kindle客户端，没有找到k4i文件

**Comment by Aeroblast** [comment]
不知道为什么，你这个只运行了一半，之后应该还有一大串，其中有提示`Saved a key to 运行目录\kindlekey.k4i` 和 `Saved decrypted book`。
检查这个exe是否完整，重新下载或者换个电脑试试？

似乎没有其他解决办法了……
