### ISSUE TITLE
为什么下载的书籍里面没有azw3文件呢？我用的是正确版本的kindle啊

### ISSUE THREAD

**Issue by Nexusliuye** [Aeroblast/UnpackKindleS#13]

**Comment by Aeroblast** [comment]
Kindle客户端下载：azw + azw.res （后者看情况，参考FAQ）
运行程序：
调用DeDRM： azw -> azw3
程序主体： azw3 [+ azw.res] -> epub

**Comment by Nexusliuye** [comment]
![image](https://user-images.githubusercontent.com/93781251/140845676-2b8cb984-6234-4f20-8e09-2a05c78e4790.png)
![image](https://user-images.githubusercontent.com/93781251/140845704-06d5af86-1a97-4a70-8a93-5d5421d0ad01.png)
就是这样的

**Comment by Aeroblast** [comment]
尝试把整个软件存到仅有英文字符的路径下。
因为那个精简版解密程序对包含英文以外字符的路径支持不好。
