### ISSUE TITLE
找不到.azw3文件

### ISSUE THREAD

**Issue by asranzalla** [Aeroblast/UnpackKindleS#16]
mykindlecontent脚本可以成功转化其他书籍，但有一本英文书无法找到azw3文件
![image](https://user-images.githubusercontent.com/28900924/172017008-bbfef326-bcad-4837-8109-c34d4d82297f.png)
最新版kindle客户端下载的，目录里长这样
![image](https://user-images.githubusercontent.com/28900924/172017069-dc69180e-87a7-4365-8ef8-9e69c30033c4.png)
#13 #14 中提到的renderer-test并没能在电脑里找到，请问该如何解决？

**Comment by Aeroblast** [comment]
是KFX格式。本工具只处理KF8。

[#14的那个链接](https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#recent-changes-to-kindle-for-pckindle-for-mac) 里有更详细的处理方法。
+ 尝试获得KF8 -> 找更旧的客户端或者删除 renderer-test （应该在 C:\Users\用户名\AppData\Local\Amazon\Kindle\application ，手头的1.28是有的）
+ 尝试处理KFX -> 看看他们的插件怎么用。在那个页面搜KFX就能找到说明。
