### ISSUE TITLE
DeDRM_tools已经更新到7.2.1，AZW3_PC_DeDRM是否需要更新下？

### ISSUE THREAD

**Issue by CruzerHP** [Aeroblast/UnpackKindleS#17]
DeDRM_tools已经更新到7.2.1，支持更新版本的PC端kindle app的加密代码了，AZW3_PC_DeDRM是否需要更新下？

**Comment by Aeroblast** [comment]
看上去没有更新，仍然是截止到1.29，一样的。

如果有发现新版的key提取，欢迎告诉我，或者直接从那边打包下脚本（这边是旧的Python2版，能用就一直没升级Python3）（怠惰）。

另外原本发布7.2.1的人已经不再维护，他说 “I shall be using noDRM's version of the tools from now on”，指的应该是 https://github.com/noDRM/DeDRM_tools
