### ISSUE TITLE
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MindController** [Aeroblast/UnpackKindleS#2]
I get this error when dropping an azw.res file onto "_Tool_Drop_Dump_azwres.bat":

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object
unpackkindles.program.main(string[] args) in program.cs - line 36
unpackkindles.program.dumphdimage(string[] args) in program.cs - line 287

Here's a screenshot of it as well:

![Untitled-2](https://user-images.githubusercontent.com/596331/70847267-96790b00-1e30-11ea-94b4-5f5b0bcd3b4e.png)

**Comment by Aeroblast** [comment]
There are really some bugs there, but I can't reproduce the NullReferenceException.
Have you tried other batches? 
If you want HD images instantly, you can convert them to epub, and then use some tools like 7-zip decompress it. Files which end with `_HD` are images you want.
