### ISSUE TITLE
AZW3转换EPUB时少了封面页及SVG调整图片大小

### ISSUE THREAD

**Issue by tassss2** [Aeroblast/UnpackKindleS#21]
不知道是软件还是KINDLE UNPACK的问题

通常问题是出在封面页并非以 embed0000.jpg命名

封面图档是有转换，但部份AZW3档转换EPUB后，XHTML档案是没有封面页 (第一个XHTML是指向第二张图)，令EPUB阅读器解读不了书本结构

图档没有加上相应的SVG编码，令图档即使人手加入封面页修正后，也会以原档尺村显示

**Comment by Aeroblast** [comment]
机制如此。

这边主要在日亚测试，很多书封面图片是最后一个图，也有很多书是第一个图做封面（漫画之类的），这个并不是确定的。

还有个情况是，有些书有封面，但不给 XHTML。当 spine 内项目数量比文档数量多一个时，我们认为日亚上架时保留封面图但删掉了封面文档，工具会拿模板补一个。数量一致的就不补，认为这个封面仅用于在 package 内指定 cover-image 。

关于手动补封面页，这个应该跟工具没啥关系了。可能看看 SVG 的画布大小和图片大小写对了没？
