### ISSUE TITLE
Tool_Drop_Dump_azwres.bat 不提取高分辨率的文件

### ISSUE THREAD

**Issue by hfizroy** [Aeroblast/UnpackKindleS#22]
提取的结果是质量为96 DPI（通用分辨率）的照片，不在300 DPI。

**Comment by Aeroblast** [comment]
工具只针对亚马逊的打包结构进行解包，不管内容是什么。

分辨率也不一定高。举个例子，日亚很多漫画的azw.res图分辨率是跟本体azw3图一样的，只是提高了JPEG的压缩参数。

**Comment by hfizroy** [comment]
感谢您的回复
