### ISSUE TITLE
应该失效了？不太懂

### ISSUE THREAD

**Issue by HarumiEna** [Aeroblast/UnpackKindleS#24]
![image](https://user-images.githubusercontent.com/98130008/229619758-2e7fd9e0-05e5-4ef2-8bd2-b861c9a957f5.png)

**Comment by Aeroblast** [comment]
AZW3_PC_DeDRM 的路径不能有中文。

目前亲测有效。亚马逊的策略在收紧，新书绕个弯子仍然可以用。~但是假如未来失效，短时间里没心思完善了，可以去看看mobileread的讨论~
