### ISSUE TITLE
Kindle For PC 1.37之后加密更新

### ISSUE THREAD

**Issue by anywugn** [Aeroblast/UnpackKindleS#25]
![9~OY3_J@1 S3$RJ({@Y)B1G](https://github.com/Aeroblast/UnpackKindleS/assets/31065340/7e835f38-fd81-4a73-8fb2-280ccb708634)
![6TN J0H515~)OL3R)SXQ3 7](https://github.com/Aeroblast/UnpackKindleS/assets/31065340/b409a289-72f7-4a2c-99da-41d3315bbb71)

您好！最近Amazon Kindle For PC进行了几次更新，现在新出版的书已经不支持1.37以下版本的Kindle For PC客户端内下载了，但是升级了最新版的Kindle For PC之后发现，对于新版的azw文件破解加密已经失效了，恳请更新

**Comment by Aeroblast** [comment]
新版只是升级了密钥的加密，资源加密没变。

简单workaround：安装旧版，跑一次程序拿到key（.k4i），在登陆的状态覆盖更新，就能正常使用。安装包什么的最好留着能用的版本。


再额外解释下，咱这个工具做的事情是格式转换，处理的格式主要是日文书在用。解加密的工具是DeDRM tools（所以发布的压缩包附带DeDRM的azw3部分的封装exe）。至于kfx（大多是英文书）也处理不了。

新的密钥获取和kfx等格式请去关注 [DeDRM_tools](https://github.com/noDRM/DeDRM_tools)  （看样子目前还没有新的）
