### ISSUE TITLE
加密方式疑似更改

### ISSUE THREAD

**Issue by asralter** [Aeroblast/UnpackKindleS#27]
从kindle下载书籍后，文件里多了个名为amzn1.drm-voucher.v1.1ec22035-a406-41c1-a5af-7fc9bb26063b的voucher文件，同时azw.res文件从一个变成四个，并且书籍和图片文件皆破解失败，这种情况是要等新方法吗？

**Comment by Aeroblast** [comment]
这个可能是KFX，可以去看看相关的资料 https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md 。

如果你在用日区，可以试着降级客户端，参考 https://github.com/Aeroblast/UnpackKindleS/issues/25 。

**Comment by asralter** [comment]
是在日区，确认过了，电子书本体是采用了kfx加密，不过插图资源确实不知道什么情况，到时降级试一下

**Comment by asralter** [comment]
pc客户端降级后，电子书和插图文件的加密方式回滚，破解成功了，感谢思路提供
