### ISSUE TITLE
有二级目录的电子书转换后目录错乱和另一个报错问题

### ISSUE THREAD

**Issue by a25694** [Aeroblast/UnpackKindleS#4]
非常感谢大佬的工具，在使用中发现了两个问题反馈一下：
第一个：有二级目录的电子书转换后目录错乱，具体表现为原属于一级目录下的二级目录全部被排列到和一级目录并列的最后面并且点击无效或位置不对，合并前的azw3文件目录是没问题的。
还有一个问题：部分电子书转换过程中红字报错，然后转换出来的epub无法打开。
红字内容如下：
[Error]Cannot Create NCX or NAV.
[Error]System.OverflowException: Arithmetic operation resulted in an overflow.
   at UnpackKindleS.Util.SubArray(Byte[] src, Int32 start, Int32 length)
   at UnpackKindleS.Epub.KindlePosToUri(Int32 fid, Int32 off)
   at UnpackKindleS.Epub.CreateNCX()
   at UnpackKindleS.Epub..ctor(Azw3File azw3, Azw6File azw6)
另外两个问题出现时单独的_Tool_Drop_Dump_azwres工具是能正常提取高清图片的。

**Comment by Aeroblast** [comment]
唔，这些情况还真没有遇到过……

二级目录应该是做过支持的（测试过一些合本版），如果出错需要具体差错看看。
报错这个，我想了一下大概是我错误兜底没做好，之后修一下；出错的原因本身也得具体看。着急看书的话可以试试删除opf文件里的`toc="ncxuks"`。

可否提供一下具体的书名或ASIN？

**Comment by a25694** [comment]
我传了两个例子的源文件到网盘，是中亚的电子书：链接: 已编辑  提取码: cvg3
其实我遇到了挺多案例，我现在是用calibre转换epub后改zip解压，然后用大佬的单独bat提取的高清图片批量改名替换底清晰图再改回epub这种笨方法

**Comment by Aeroblast** [comment]
啊，抱歉，这个是没有解密的，需要解密过的azw3才能测试。运行过工具应该会在azw文件旁边出现
azw3。

中亚确实没测试过，测的全都是日亚……

**Comment by a25694** [comment]
抱歉，我也想到不该直接传那些的，已经重新传azw3了，还是那个地址。选这两个因为文件比较小方便，其实遇到过一两百M的也是，但azw3可以正确打开的。日亚我只用过几个目前没问题。

**Comment by Aeroblast** [comment]
我大概搞清楚问题了，不过修复可能还需要一阵子……

文件记得删掉，里面是包含账号水印的。

**Comment by a25694** [comment]
好的，谢谢了

**Comment by Aeroblast** [comment]
修复： https://github.com/Aeroblast/UnpackKindleS/releases/tag/20210107

大概没问题了

**Comment by a25694** [comment]
> 修复： https://github.com/Aeroblast/UnpackKindleS/releases/tag/20210107
> 
> 大概没问题了

才看到消息，非常感谢，测试了一下目录没问题了；另外之前提到的第二个问题，因红字报错后的epub可以用除calibre外其他阅读器正常打开使用，估计是calibre的问题，这种情况在calibre打开别人分享的电子书偶尔也会遇到。

**Comment by Aeroblast** [comment]
第二个问题其实也是目录的问题，这次修复可能也一起解决了，可以试试。如果还有报错的话，我再看看。

**Comment by a25694** [comment]
> 第二个问题其实也是目录的问题，这次修复可能也一起解决了，可以试试。如果还有报错的话，我再看看。

新版本工具目前只遇到了个别例子，例如中亚的这个ASIN : B084212Z48。转换合并高清图后的epub在calibre打不开，可以用sumatra等软件打开，不影响使用。不过只有calibre打不开这种事一些别人自制的epub也出现过，不知是不是calibre对epub格式有严格要求还是怎么的。

**Comment by ghost** [comment]
@Aeroblast 
> 第二个问题其实也是目录的问题，这次修复可能也一起解决了，可以试试。如果还有报错的话，我再看看。

Hello, 我也遇到了转换epub时出现Error，且输出的epub无法用calibre打开的情况。

- 版本：[诸多改进](https://github.com/Aeroblast/UnpackKindleS/releases/tag/20210316l)
- 出错书籍：https://www.amazon.cn/gp/product/B0919SP879
- Error输出：
```
[Error]Cannot Create NCX or NAV.
[Error]System.NullReferenceException: Object reference not set to an instance of an object.
   at UnpackKindleS.Epub.CreateIndexDoc()
   at UnpackKindleS.Epub..ctor(Azw3File azw3, Azw6File azw6, Boolean rename_xhtml_with_id)
```

**Comment by Aeroblast** [comment]
啊，之前没遇到过3级目录，中间的层有不一样的数据结构。
修复了。

**Comment by ghost** [comment]
我这边用[20210331](https://github.com/Aeroblast/UnpackKindleS/releases/tag/20210331)测试了两本有3级目录的书籍，都没有问题了，感谢修复.
