### ISSUE TITLE
".epub" only shows the cover

### ISSUE THREAD

**Issue by eXmendiC** [Aeroblast/UnpackKindleS#6]
It does create a fine "_nodrm.azw3" file, but the conversion to ".epub" seems to fail.
Kindle version is 1.26.0
UnpackKindleS version: 20210422

There is only the cover image left.
B08J2MTDGP_EBOK.azw - 69,6 MB
B08J2MTDGP_EBOK_nodrm.azw3 - 69,6 MB
[Kodama, Naoko] I married my best friend to shut my parents up.epub - 676 KB

That happed to me for three e-books so far (everything else worked fine):
https://www.amazon.de/dp/B08J2MTDGP
https://www.amazon.de/dp/B08V13ZHX9
https://www.amazon.de/dp/B09232DQKW

**Comment by Aeroblast** [comment]
Could you provide any further info of the failure? Find 'lastrun.log' or just copy the output of the commandline window, especially the red part if there is any. You can delete something like 'Watermark' to protect your pravicy.

**Comment by eXmendiC** [comment]
I didn't post it, because I wasn't sure if there is sensitive data in it. 
Here the log file for the three files: https://pastebin.com/Wa3XJVvy (auto delete in a week)
As you suggested, I've removed the "Watermark" part.

**Comment by Aeroblast** [comment]
I see. It seems that most images are not referred by the text of epub, so they are not included in epub.
I wonder if there are any image links that I have not seen before (since I could only purchase books in amazon japan). I need to check it. Unzip the epub file (actually it is a zip file, some soft like 7-zip should work), and xhtml files will be in `OEBPS\Text\ `. Any of them is ok, except cover.xhtml .

**Comment by eXmendiC** [comment]
Here: https://pastebin.com/UZzKMM2r

**Comment by Aeroblast** [comment]
I see. Where `kindle:embed:0051?mime=image/jpg` should be something like `../Images/embed0001.jpg`. 
Using background to display a image, so wired... Whatever, I will fix it recently.  Thank you for your feedback.

**Comment by Aeroblast** [comment]
There is a pre-release now: https://github.com/Aeroblast/UnpackKindleS/releases/tag/20210604
It should work. Tell me if it still has any problems.

**Comment by eXmendiC** [comment]
Works fine for me. Closed the ticket, because the issue isn't present anymore.
