### ISSUE TITLE
合并中亚Kindle电子书报错

### ISSUE THREAD

**Issue by LzNOHentai** [Aeroblast/UnpackKindleS#8]
Kindle for PC 版本：1.32.0(61109)
电子书来源：Amazon.cn Kindle商店
问题描述：破解drm及提取azwres图片看起来没有问题，My Kindle Content对应目录中生成了无drm的azw3文件，单独提取azwres高清图片也是成功的，问题似乎出在合并转换epub这一过程中。

log：

> AlfCrypto not found. Using python PC1 implementation.
> MobiDeDrm v0.42.
> Copyright  2008-2017 The Dark Reverser, Apprentice Harper et al.
> AlfCrypto not found. Using python PC1 implementation.
> Decrypting Kindle Format 8 ebook
> Got DSN key from database C:\Users\Lenovo\Desktop\UnpackKindleS_Release20210604_win_x64_AZW3DeDRM\kindlekey.k4i
> Found 4 keys to try after 0.0 seconds
> Crypto Type is: 2
> File is encoded with PID +WsMx/1x6S.
> Decrypting. Please wait . . . done
> Decryption succeeded after 0.4 seconds
> Saved decrypted book after 0.4 seconds
> ==============START===============
>  unknown id 547:496E4D656D6F7279
>  unknown id 548:496E4D656D6F7279
>  unknown id 405:00
>  unknown id 407:0000000000000000
>  unknown id 403:01
> System.Exception: Unhandled Error at INDX
>    at UnpackKindleS.Azw3File.ProcessIndex()
>    at UnpackKindleS.Azw3File..ctor(String path)
>    at UnpackKindleS.Program.ProcPath(String[] args)
>    at UnpackKindleS.Program.ProcBatch(String[] args)

**Comment by Aeroblast** [comment]
已修复
