### ISSUE TITLE
可否提供自定义输出文件名的功能

### ISSUE THREAD

**Issue by DANA-Iclucia** [Aeroblast/UnpackKindleS#9]
抑或是我没有发现怎么操作，如果是这样，还望谅解。

现在输出的文件都是固定格式的文件名，不能像calibre那样自定义输出的文件名。
而且，个人认为是个问题的点是，现在输出的文件名的作者只会读取单一一位作者，而很多日轻作品在kindle中都会显示多位作者，尤其是轻改漫画之类的。

不知道能否调整？

感谢。

**Comment by Aeroblast** [comment]
目前认为，只输出一个作者比较合适，绝大多数情况够用，也不会因为极端情况翻车。遇到アンソロジー或者合本版试读，十几个作者总不能全都弄进文件名吧。

另外，出版社和亚马逊本身在元数据上也不是很走心，商品页面的插画师很多就没在实际书的数据里写，而出版社也没有按照标准分配“插画师”等角色，而是全都写”作者“。

至于输出格式……感觉这个超出专用工具的范畴了。
